export interface CountryInfo {
  /** ISO-3166-1 numeric code, zero-padded to 3 digits — matches world-atlas topojson feature `id` (e.g. "840" for the US). */
  numericId: string
  /** Human-readable English name for tooltips, e.g. "United States". */
  name: string
}

export const COUNTRY_CODES: Record<string, CountryInfo> = {
  AD: { numericId: '020', name: 'Andorra' },
  AE: { numericId: '784', name: 'UAE' },
  AF: { numericId: '004', name: 'Afghanistan' },
  AG: { numericId: '028', name: 'Antigua and Barbuda' },
  AI: { numericId: '660', name: 'Anguilla' },
  AL: { numericId: '008', name: 'Albania' },
  AM: { numericId: '051', name: 'Armenia' },
  AO: { numericId: '024', name: 'Angola' },
  AQ: { numericId: '010', name: 'Antarctica' },
  AR: { numericId: '032', name: 'Argentina' },
  AS: { numericId: '016', name: 'American Samoa' },
  AT: { numericId: '040', name: 'Austria' },
  AU: { numericId: '036', name: 'Australia' },
  AW: { numericId: '533', name: 'Aruba' },
  AX: { numericId: '248', name: 'Aland Islands' },
  AZ: { numericId: '031', name: 'Azerbaijan' },
  BA: { numericId: '070', name: 'Bosnia and Herzegovina' },
  BB: { numericId: '052', name: 'Barbados' },
  BD: { numericId: '050', name: 'Bangladesh' },
  BE: { numericId: '056', name: 'Belgium' },
  BF: { numericId: '854', name: 'Burkina Faso' },
  BG: { numericId: '100', name: 'Bulgaria' },
  BH: { numericId: '048', name: 'Bahrain' },
  BI: { numericId: '108', name: 'Burundi' },
  BJ: { numericId: '204', name: 'Benin' },
  BL: { numericId: '652', name: 'Saint Barthélemy' },
  BM: { numericId: '060', name: 'Bermuda' },
  BN: { numericId: '096', name: 'Brunei' },
  BO: { numericId: '068', name: 'Bolivia' },
  BQ: { numericId: '535', name: 'Bonaire, Sint Eustatius and Saba' },
  BR: { numericId: '076', name: 'Brazil' },
  BS: { numericId: '044', name: 'Bahamas' },
  BT: { numericId: '064', name: 'Bhutan' },
  BV: { numericId: '074', name: 'Bouvet Island' },
  BW: { numericId: '072', name: 'Botswana' },
  BY: { numericId: '112', name: 'Belarus' },
  BZ: { numericId: '084', name: 'Belize' },
  CA: { numericId: '124', name: 'Canada' },
  CC: { numericId: '166', name: 'Cocos (Keeling) Islands' },
  CD: { numericId: '180', name: 'Congo (DRC)' },
  CF: { numericId: '140', name: 'Central African Republic' },
  CG: { numericId: '178', name: 'Congo (Republic)' },
  CH: { numericId: '756', name: 'Switzerland' },
  CI: { numericId: '384', name: 'Côte d\'Ivoire' },
  CK: { numericId: '184', name: 'Cook Islands' },
  CL: { numericId: '152', name: 'Chile' },
  CM: { numericId: '120', name: 'Cameroon' },
  CN: { numericId: '156', name: 'China' },
  CO: { numericId: '170', name: 'Colombia' },
  CR: { numericId: '188', name: 'Costa Rica' },
  CU: { numericId: '192', name: 'Cuba' },
  CV: { numericId: '132', name: 'Cape Verde' },
  CW: { numericId: '531', name: 'Curaçao' },
  CX: { numericId: '162', name: 'Christmas Island' },
  CY: { numericId: '196', name: 'Cyprus' },
  CZ: { numericId: '203', name: 'Czechia' },
  DE: { numericId: '276', name: 'Germany' },
  DJ: { numericId: '262', name: 'Djibouti' },
  DK: { numericId: '208', name: 'Denmark' },
  DM: { numericId: '212', name: 'Dominica' },
  DO: { numericId: '214', name: 'Dominican Republic' },
  DZ: { numericId: '012', name: 'Algeria' },
  EC: { numericId: '218', name: 'Ecuador' },
  EE: { numericId: '233', name: 'Estonia' },
  EG: { numericId: '818', name: 'Egypt' },
  EH: { numericId: '732', name: 'Western Sahara' },
  ER: { numericId: '232', name: 'Eritrea' },
  ES: { numericId: '724', name: 'Spain' },
  ET: { numericId: '231', name: 'Ethiopia' },
  FI: { numericId: '246', name: 'Finland' },
  FJ: { numericId: '242', name: 'Fiji' },
  FK: { numericId: '238', name: 'Falkland Islands (Malvinas)' },
  FM: { numericId: '583', name: 'Micronesia' },
  FO: { numericId: '234', name: 'Faroe Islands' },
  FR: { numericId: '250', name: 'France' },
  GA: { numericId: '266', name: 'Gabon' },
  GB: { numericId: '826', name: 'United Kingdom' },
  GD: { numericId: '308', name: 'Grenada' },
  GE: { numericId: '268', name: 'Georgia' },
  GF: { numericId: '254', name: 'French Guiana' },
  GG: { numericId: '831', name: 'Guernsey' },
  GH: { numericId: '288', name: 'Ghana' },
  GI: { numericId: '292', name: 'Gibraltar' },
  GL: { numericId: '304', name: 'Greenland' },
  GM: { numericId: '270', name: 'The Gambia' },
  GN: { numericId: '324', name: 'Guinea' },
  GP: { numericId: '312', name: 'Guadeloupe' },
  GQ: { numericId: '226', name: 'Equatorial Guinea' },
  GR: { numericId: '300', name: 'Greece' },
  GS: { numericId: '239', name: 'South Georgia and the South Sandwich Islands' },
  GT: { numericId: '320', name: 'Guatemala' },
  GU: { numericId: '316', name: 'Guam' },
  GW: { numericId: '624', name: 'Guinea-Bissau' },
  GY: { numericId: '328', name: 'Guyana' },
  HK: { numericId: '344', name: 'Hong Kong' },
  HM: { numericId: '334', name: 'Heard Island and McDonald Islands' },
  HN: { numericId: '340', name: 'Honduras' },
  HR: { numericId: '191', name: 'Croatia' },
  HT: { numericId: '332', name: 'Haiti' },
  HU: { numericId: '348', name: 'Hungary' },
  ID: { numericId: '360', name: 'Indonesia' },
  IE: { numericId: '372', name: 'Ireland' },
  IL: { numericId: '376', name: 'Israel' },
  IM: { numericId: '833', name: 'Isle of Man' },
  IN: { numericId: '356', name: 'India' },
  IO: { numericId: '086', name: 'British Indian Ocean Territory' },
  IQ: { numericId: '368', name: 'Iraq' },
  IR: { numericId: '364', name: 'Iran' },
  IS: { numericId: '352', name: 'Iceland' },
  IT: { numericId: '380', name: 'Italy' },
  JE: { numericId: '832', name: 'Jersey' },
  JM: { numericId: '388', name: 'Jamaica' },
  JO: { numericId: '400', name: 'Jordan' },
  JP: { numericId: '392', name: 'Japan' },
  KE: { numericId: '404', name: 'Kenya' },
  KG: { numericId: '417', name: 'Kyrgyzstan' },
  KH: { numericId: '116', name: 'Cambodia' },
  KI: { numericId: '296', name: 'Kiribati' },
  KM: { numericId: '174', name: 'Comoros' },
  KN: { numericId: '659', name: 'Saint Kitts and Nevis' },
  KP: { numericId: '408', name: 'North Korea' },
  KR: { numericId: '410', name: 'South Korea' },
  KW: { numericId: '414', name: 'Kuwait' },
  KY: { numericId: '136', name: 'Cayman Islands' },
  KZ: { numericId: '398', name: 'Kazakhstan' },
  LA: { numericId: '418', name: 'Laos' },
  LB: { numericId: '422', name: 'Lebanon' },
  LC: { numericId: '662', name: 'Saint Lucia' },
  LI: { numericId: '438', name: 'Liechtenstein' },
  LK: { numericId: '144', name: 'Sri Lanka' },
  LR: { numericId: '430', name: 'Liberia' },
  LS: { numericId: '426', name: 'Lesotho' },
  LT: { numericId: '440', name: 'Lithuania' },
  LU: { numericId: '442', name: 'Luxembourg' },
  LV: { numericId: '428', name: 'Latvia' },
  LY: { numericId: '434', name: 'Libya' },
  MA: { numericId: '504', name: 'Morocco' },
  MC: { numericId: '492', name: 'Monaco' },
  MD: { numericId: '498', name: 'Moldova' },
  ME: { numericId: '499', name: 'Montenegro' },
  MF: { numericId: '663', name: 'Saint Martin (French part)' },
  MG: { numericId: '450', name: 'Madagascar' },
  MH: { numericId: '584', name: 'Marshall Islands' },
  MK: { numericId: '807', name: 'North Macedonia' },
  ML: { numericId: '466', name: 'Mali' },
  MM: { numericId: '104', name: 'Myanmar' },
  MN: { numericId: '496', name: 'Mongolia' },
  MO: { numericId: '446', name: 'Macao' },
  MP: { numericId: '580', name: 'Northern Mariana Islands' },
  MQ: { numericId: '474', name: 'Martinique' },
  MR: { numericId: '478', name: 'Mauritania' },
  MS: { numericId: '500', name: 'Montserrat' },
  MT: { numericId: '470', name: 'Malta' },
  MU: { numericId: '480', name: 'Mauritius' },
  MV: { numericId: '462', name: 'Maldives' },
  MW: { numericId: '454', name: 'Malawi' },
  MX: { numericId: '484', name: 'Mexico' },
  MY: { numericId: '458', name: 'Malaysia' },
  MZ: { numericId: '508', name: 'Mozambique' },
  NA: { numericId: '516', name: 'Namibia' },
  NC: { numericId: '540', name: 'New Caledonia' },
  NE: { numericId: '562', name: 'Niger' },
  NF: { numericId: '574', name: 'Norfolk Island' },
  NG: { numericId: '566', name: 'Nigeria' },
  NI: { numericId: '558', name: 'Nicaragua' },
  NL: { numericId: '528', name: 'The Netherlands' },
  NO: { numericId: '578', name: 'Norway' },
  NP: { numericId: '524', name: 'Nepal' },
  NR: { numericId: '520', name: 'Nauru' },
  NU: { numericId: '570', name: 'Niue' },
  NZ: { numericId: '554', name: 'New Zealand' },
  OM: { numericId: '512', name: 'Oman' },
  PA: { numericId: '591', name: 'Panama' },
  PE: { numericId: '604', name: 'Peru' },
  PF: { numericId: '258', name: 'French Polynesia' },
  PG: { numericId: '598', name: 'Papua New Guinea' },
  PH: { numericId: '608', name: 'Philippines' },
  PK: { numericId: '586', name: 'Pakistan' },
  PL: { numericId: '616', name: 'Poland' },
  PM: { numericId: '666', name: 'Saint Pierre and Miquelon' },
  PN: { numericId: '612', name: 'Pitcairn Islands' },
  PR: { numericId: '630', name: 'Puerto Rico' },
  PS: { numericId: '275', name: 'Palestine' },
  PT: { numericId: '620', name: 'Portugal' },
  PW: { numericId: '585', name: 'Palau' },
  PY: { numericId: '600', name: 'Paraguay' },
  QA: { numericId: '634', name: 'Qatar' },
  RE: { numericId: '638', name: 'Reunion' },
  RO: { numericId: '642', name: 'Romania' },
  RS: { numericId: '688', name: 'Serbia' },
  RU: { numericId: '643', name: 'Russia' },
  RW: { numericId: '646', name: 'Rwanda' },
  SA: { numericId: '682', name: 'Saudi Arabia' },
  SB: { numericId: '090', name: 'Solomon Islands' },
  SC: { numericId: '690', name: 'Seychelles' },
  SD: { numericId: '729', name: 'Sudan' },
  SE: { numericId: '752', name: 'Sweden' },
  SG: { numericId: '702', name: 'Singapore' },
  SH: { numericId: '654', name: 'Saint Helena' },
  SI: { numericId: '705', name: 'Slovenia' },
  SJ: { numericId: '744', name: 'Svalbard and Jan Mayen' },
  SK: { numericId: '703', name: 'Slovakia' },
  SL: { numericId: '694', name: 'Sierra Leone' },
  SM: { numericId: '674', name: 'San Marino' },
  SN: { numericId: '686', name: 'Senegal' },
  SO: { numericId: '706', name: 'Somalia' },
  SR: { numericId: '740', name: 'Suriname' },
  SS: { numericId: '728', name: 'South Sudan' },
  ST: { numericId: '678', name: 'Sao Tome and Principe' },
  SV: { numericId: '222', name: 'El Salvador' },
  SX: { numericId: '534', name: 'Sint Maarten (Dutch part)' },
  SY: { numericId: '760', name: 'Syria' },
  SZ: { numericId: '748', name: 'Eswatini' },
  TC: { numericId: '796', name: 'Turks and Caicos Islands' },
  TD: { numericId: '148', name: 'Chad' },
  TF: { numericId: '260', name: 'French Southern Territories' },
  TG: { numericId: '768', name: 'Togo' },
  TH: { numericId: '764', name: 'Thailand' },
  TJ: { numericId: '762', name: 'Tajikistan' },
  TK: { numericId: '772', name: 'Tokelau' },
  TL: { numericId: '626', name: 'Timor-Leste' },
  TM: { numericId: '795', name: 'Turkmenistan' },
  TN: { numericId: '788', name: 'Tunisia' },
  TO: { numericId: '776', name: 'Tonga' },
  TR: { numericId: '792', name: 'Turkey' },
  TT: { numericId: '780', name: 'Trinidad and Tobago' },
  TV: { numericId: '798', name: 'Tuvalu' },
  TW: { numericId: '158', name: 'Taiwan' },
  TZ: { numericId: '834', name: 'Tanzania' },
  UA: { numericId: '804', name: 'Ukraine' },
  UG: { numericId: '800', name: 'Uganda' },
  UM: { numericId: '581', name: 'United States Minor Outlying Islands' },
  US: { numericId: '840', name: 'United States' },
  UY: { numericId: '858', name: 'Uruguay' },
  UZ: { numericId: '860', name: 'Uzbekistan' },
  VA: { numericId: '336', name: 'Vatican City' },
  VC: { numericId: '670', name: 'Saint Vincent and the Grenadines' },
  VE: { numericId: '862', name: 'Venezuela' },
  VG: { numericId: '092', name: 'Virgin Islands, British' },
  VI: { numericId: '850', name: 'Virgin Islands, U.S.' },
  VN: { numericId: '704', name: 'Vietnam' },
  VU: { numericId: '548', name: 'Vanuatu' },
  WF: { numericId: '876', name: 'Wallis and Futuna' },
  WS: { numericId: '882', name: 'Samoa' },
  XK: { numericId: '983', name: 'Kosovo' },
  YE: { numericId: '887', name: 'Yemen' },
  YT: { numericId: '175', name: 'Mayotte' },
  ZA: { numericId: '710', name: 'South Africa' },
  ZM: { numericId: '894', name: 'Zambia' },
  ZW: { numericId: '716', name: 'Zimbabwe' },
}

export function lookupCountry(alpha2: string): CountryInfo | null {
  return COUNTRY_CODES[alpha2.toUpperCase()] ?? null
}
